### ISSUE TITLE
Ideas on best usage with CI

### ISSUE THREAD

**Issue by msrd0** [msrd0/cargo-doc2readme#19]
Given that the generated readme depends on a variety of inputs other than the input source, e.g. the exact version of libraries used, there are many ways a readme can change. Therefore, using a CI that just checks the readme didn't change byte for byte, like you'd do with rustfmt, might not be the best solution. At the same time, you'll want your readme to stay up to date.

These things came to my mind, but there might be more alternatives:

 - Keep running a byte-for-byte CI check. This means that contributions that don't change any documentation or dependencies might fail the CI because some random dependency has released a new semver-compatible version. I don't like this.
 - Introduce some _lock file_ that pins dependencies independently from the `Cargo.lock` file (which, at least for libraries, is usually not version-controlled). This way CI only fails when it should, but the readme might link to outdated documentation for dependencies.
 - Run the CI not as a check but as an update, on a schedule and/or on every commit.

If you have any thoughts, please share them below.

**Comment by niluxv** [comment]
I don't really like the idea of *another* lock file hanging around (it has to be checked in to git and regularly updated, which is easy to forget; the entire idea of running doc2readme in CI is to not forget it).
What is exactly the problem of a byte-to-byte check? I can think of two things:
1. Changes in the way doc2readme formats the readme when it is updated.
2. Changes in the link section if the readme links documentation of other crates and those crates publish a semver-compatible release.

Ideally, the output of doc2readme would be stable so 1. is not a problem (and also not solved by the lock file). The severity of 2. depends on how often a crate references items in other crates in the main documentation. I do think this is highly uncommon, except maybe for `core`/`std` (but for the standard library the links are fixed to stable and do not include a version number, so that is no problem either).

I do like the third option, but it is entirely orthogonal to a `--check` flag. A `--check` flag could also be useful in local workflows, when one wants to know whether the readme is up-to-date without possibly changing it.

**Comment by msrd0** [comment]
I know, it'd be nice if the output was stable. However, by the nature of selecting the latest available compatible dependency version and creating a docs.rs link containing it, it can't really be stable. So the problem with bytewise comparison is that the links section can change, even when using the same version of cargo-doc2readme and not changing any files in your project. This is, at least with the crates I use, a big deal and has lead to a few failed pipelines that shouldn't have failed if a "better" check than bytewise would've been used.

Another idea might be to read the existing file and compare it with manual logic, so that the comparison is independent of the dependency version selected. This could be accomplished for example by adding a hash of the template file and a hash of the documentation read from the lib.rs file and add that as a comment to the generated readme.

I'd best like the 3rd option with some sort of post-pr-but-pre-merge CI run, that runs after you accept a PR and before it merges onto your default branch. However, I haven't heard that GitHub plans on adding support for this, so this will stay a dream for the time being.

**Comment by msrd0** [comment]
Version `0.1.0` includes a check flag. It uses a lock inlied into the readme, and falls back to bytewise comparison if the lock is missing. The lock will only be included if at least one link to docs.rs/crates.io was used in the readme.
